name: Docker Build and Push Pipeline

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version tag for images'
        required: true
        default: 'latest'
      registry:
        description: 'Docker registry'
        required: true
        default: 'slowickipiotr'

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      DOCKER_REGISTRY: ${{ github.event.inputs.registry }}
      UI_TAG: ui-${{ github.event.inputs.version }}
      API_TAG: api-${{ github.event.inputs.version }}

    steps:
    - uses: actions/checkout@v3

    - uses: docker/setup-buildx-action@v3

    - uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and test
      run: |
        docker compose build --no-cache
        docker compose up -d
        sleep 10
        docker compose ps
        docker compose logs
        docker compose down

    - name: Push images
      run: |
        docker compose push